### ISSUE TITLE
default extractMeta implementation is truncating additional metadata

### ISSUE THREAD

**Issue by rafalp** [dustinfarris/ember-django-adapter#111]
Use case: invoicing app asks API for list of invoices. Metadata includes pagination data as well as dialy, monthly and yearly turnarounds that can be displayed somewhere near list. However default extractMeta implementation used by Ember-Django adapter assumes that metadata will be used only for pagination, and thus discards other meta, breaking contract promised by Ember's docs.

**Comment by benkonrath** [comment]
I didn't consider that people use the metadata for things other than pagination but you seem to have a good use case. Can you send me a link to the Ember documentation you mention? Thanks.

**Comment by benkonrath** [comment]
You can solve this by overriding `extractMeta` for just the `invoice` record type. You can generate a `DRFSerializer` for `invoice` with this ember-cli command:

```bash
ember generate drf-serializer invoice
```

Then add your own metadata where I've indicated and also delete the extra properties (again as indicated). This is just off the top of my head so I haven't tested it.

```js
// app/serializer/invoice.js
import DRFSerializer from './drf';

export default DRFSerializer.extend({
  extractMeta: function(store, type, payload) {
    if (payload && payload.results) {
      // Sets the metadata for the type.
      store.setMetadataFor(type, {
        count: payload.count,
        next: this.extractPageNumber(payload.next),
        previous:  this.extractPageNumber(payload.previous),

        // Add your custom metadata here.
      });

      // Keep ember data from trying to parse the metadata as a records
      delete payload.count;
      delete payload.next;
      delete payload.previous;

      // Delete your custom metadata properties here.
    }
  }
});
```
I'm still interested to see the documentation to know if we should be setting the unknown metadata so that you can avoid doing this. Thanks.

**Comment by rafalp** [comment]
Hey there!

http://guides.emberjs.com/v1.12.0/models/handling-metadata/

The way I understand this if backend provides `meta` key in json response, that key's values are treated as metadata and are automatically put into meta for type.

Taking from there I've assumed that because django adapter is middleman translating DRF's json for Ember-Data json, and Rest Framework is not using meta key on its responses, adapter could treat all other keys not belonging to `results` as metadata. But I admit this interpretation may be debatable. :]

It's indeed easy to get fixed by onself. In fact it took me 5 minutes to write custom meta extractor in my app serializer (I'm doing heavy use on metadata in my api responses).

**Comment by benkonrath** [comment]
I agree with your analysis; extra metadata should be included with the metadata. I'll try to fix this for the next release. Thanks.
