### ISSUE TITLE
Modify error object to contain a source pointer when "non_field_errors" in DRF response

### ISSUE THREAD

**Issue by holandes22** [dustinfarris/ember-django-adapter#113]
See discussion in #108 

Instead of using meta to store the non field errors key, we will use the source object (to be consistent with validation errors)

```js
{
  detail: "non field error goes here",
  source: { pointer: "data" },
  title: "General error"  // need better phrasing here, Maybe Non-field errors?
}
```

**Comment by dustinfarris** [comment]
Now that #114 is merged we can take another look at this.

**Comment by holandes22** [comment]
Yes, sorry long time. Been crazy at my 9 to 5. I'll revisit this during the weekend and open a PR
