### ISSUE TITLE
Q about embedded records

### ISSUE THREAD

**Issue by nanuxbe** [dustinfarris/ember-django-adapter#118]
Hi,
I was wondering if you could enlighten me a bit about embedded records write limitations? Does it come from an ember-data limitation or a drf limitation or something else.

Thanks :-)

**Comment by benkonrath** [comment]
The limitation is in Django REST Framework. There's some usefule information about this in #105 with a potential solution.

**Comment by nanuxbe** [comment]
@benkonrath thanks for your reply.
now I remember already seeing that method somewhere but it doesn't fit my needs as what I'd like to do is save a record at the same time as its hasMany related records inside a transaction and either report success on the whole thing or rollback the entire transaction if any of the related record (or the main record) fails.

But seeing that solution again gave me the idea to investigate the possibility of using [BulkListSerializer](https://github.com/miki725/django-rest-framework-bulk/blob/master/rest_framework_bulk/drf3/serializers.py) to (de-)serialize embedded records.

**Comment by benkonrath** [comment]
Nice that you found something that could work. Feel free to reopen this issue if you feel your question hasn't been answered.
