### ISSUE TITLE
Version 1.0 roadmap

### ISSUE THREAD

**Issue by holandes22** [dustinfarris/ember-django-adapter#122]
Hi guys,

Just opening this ticket to track what we need to release 1.0

Are we going to wait for Ember and Ember data 2.0 to come out or do you prefer to do a release before that?

The adapter is quite stable now so I think is time for a release.

Any big issues we need to address before that? We have 4 issues opened, do we need to close them all before 1.0?

**Comment by benkonrath** [comment]
For me #113 should be done and if possible #116. I'd like to stick with our original plan of releasing 1.0 for Ember 1.13. We can bump to 2.0 for incompatible changes that land in Ember Data 2.

**Comment by dustinfarris** [comment]
Agree with @benkonrath.  I want to release 1.0 asap; but the 2 issues mentioned need to be resolved first.

**Comment by jpadilla** [comment]
@benkonrath @dustinfarris went ahead and tried progressing both those issues with #123 and #124.

**Comment by dustinfarris** [comment]
Version 1.0.0 released in https://github.com/dustinfarris/ember-django-adapter/commit/db320476e7af8c01ac274d79b80c53005ab39e33

Really great work everyone!

/thanks @benkonrath @holandes22 @jpadilla @gone @citmusa and everyone else who contributed.  You guys rock!

**Comment by benkonrath** [comment]
@dustinfarris Thanks to you too! :+1:
