### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by erichonkanen** [dustinfarris/ember-django-adapter#127]
hello,

I am using this package and receiving this deprecation warning which I think comes from this package.. Just fyi! 

```DEPRECATION: Your custom serializer uses the old version of the Serializer API, with `extract` hooks. Please upgrade your serializers to the new Serializer API using `normalizeResponse` hooks instead.```

Im using latest ember/cli

**Comment by dustinfarris** [comment]
Are you using ember-django-adapter v1.0.0?  This was addressed in the latest release.

**Comment by erichonkanen** [comment]
let me check

**Comment by erichonkanen** [comment]
nope was using 0.5.6, thanks!

**Comment by dustinfarris** [comment]
Great!  Be sure to check out the release notes when you have a second:

https://github.com/dustinfarris/ember-django-adapter/releases/tag/v1.0.0
