### ISSUE TITLE
Embedded Records

### ISSUE THREAD

**Issue by mikkezavala** [dustinfarris/ember-django-adapter#129]
Hi there, I've been trying to make that work, I have the adapter, and the relationships on the model,
but when it comes to retrieve the data the parent model gets from Django and inside comes the nested data, then when I try to access the embedded model/records, triggers again the queries (nested/1/, nested/2/) 
Why? It isn't supposed gets mapped from the parent to the related model, or I got it wrong?
I've followed the documentation, here and/from ember, but seems to have same behavior.
Thanks!

**Comment by dustinfarris** [comment]
Hi there.  Can you share what your model looks like in Ember?  Also the query you are using to retrieve the information.

**Comment by mikkezavala** [comment]
Sure :) Thanks a lot!
Just a really simple example of what I'm experiencing, also, when I remove the "async: true/false" some warnings come up.

```javascript
// .../models/section.js
import DS from 'ember-data';

export default DS.Model.extend({
    name: DS.attr('string'),
    highlights: DS.hasMany('highlight')
});
```

```javascript
// .../models/highlight.js
import DS from 'ember-data';

export default DS.Model.extend({
    section: DS.belongsTo('section'),
    slug_name: DS.attr('string'),
    image: DS.attr('string'),
    title: DS.attr('string'),
    caption: DS.attr('string')
});

```

The main REST request
```javascript
// http://host.../api/sections/1/
{
    "id": 1,
    "name": "Home",
    "highlights": [{
        "id": 2,
        "slug_name": "sandos-caracol",
        "image": "http://localhost:8000/media/images/highlight/2015-04-15/Astormiscoming__-_3840x2400_16x10_e7qIFO1.jpg",
        "title": "Sandos 70 % Off",
        "caption": "Some Caption...."
        },{
        "id": 4,
        "slug_name": "sandos-playacar",
        "image": "http://localhost:8000/media/images/highlight/2015-04-15/Astormiscoming__-_3840x2400_16x10_e7qIFO1.jpg",
        "title": "Sandos 70% Off",
        "caption": "Some Caption...."
    }]
}
```
And my /app/serializers/section.js looks like:
```javascript
// /app/serializers/section.js
import DRFSerializer from './drf';
import DS from 'ember-data';

export default DRFSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    highlights: { embedded: 'always' }
  }
});
```
then when retrieving the "highlights" node/model:
triggers the respective REST Request for each "highlight"
** http://host.../api/highlights/2/ **
** http://host.../api/highlights/4/ **

**Comment by kevinwmerritt** [comment]
@mikkezavala try:

```
export default DRFSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    highlights: { serialize: 'records', deserialize: 'records' }
  }
});
```

```embedded: 'always'``` was not working for me either.

**Comment by mikkezavala** [comment]
@kevinwmerritt That works! on ember 1.13.1, but in 1.13.7 worked with embedded: 'always', weird isn't?
Thanks guys for the help, would be great to keep this as a docs too, I have several colleges that had this issue too.!

**Comment by dustinfarris** [comment]
It sounds like a bug in Ember Data.  Are you saying you do or do not experience this issue in 1.13.7?

**Comment by mikkezavala** [comment]
Yes, it looks like maybe the problems is in Ember Data, The problem appears on 1.13.1, but in 1.13.7 I don't have the issue, works perfectly
