### ISSUE TITLE
serializer.pushPayload is not a function

### ISSUE THREAD

**Issue by erichonkanen** [dustinfarris/ember-django-adapter#132]
hello,

I am trying to push a record to the store that I get from a regular ajax callback.. tried using pushPayload but get `Uncaught TypeError: serializer.pushPayload is not a function`

any ideas why?

```
      request.done (response)=>
        response['id'] = response.username
        @store.pushPayload 'user', response
```

**Comment by erichonkanen** [comment]
this seems to work though.. is there anyway to use the adapter from this package to automatically create json-api doc from my api response?

```      request.done (response)=>
        # Form json-api object and push into the store.
        data =
          'type': 'user'
          'id': response.username
          'attributes':
            'full_name': response.full_name
            'username': response.username
            'email': response.email
            'uid': response.uid
        @store.push data
```

**Comment by dustinfarris** [comment]
We are considering extending DS.RESTAdapter and DS.RESTSerializer (see #128).  pushPayload would be an added benefit of doing that.  Otherwise we'll have to implement this in EDA.  Thanks for reporting this.

**Comment by erichonkanen** [comment]
ok cool, what is eda?

**Comment by dustinfarris** [comment]
Ember Django Adapter :-)

**Comment by erichonkanen** [comment]
doh duh! hah ok thanks

**Comment by benkonrath** [comment]
@erichonkanen Can you test the PR in #133 to see if it solves this problem? Thanks.

**Comment by erichonkanen** [comment]
@benkonrath yep uno momento

**Comment by benkonrath** [comment]
@erichonkanen Please reopen this issue if it's still causing problems for you.

**Comment by erichonkanen** [comment]
what is the recommended way to push an object into the store that is returned from an $.ajax() request? I seem to be getting issues using latest version:

`WARNING: Encountered "data" in payload, but no model was found for model name "datum" (resolved model name using client-web@serializer:user:.modelNameFromPayloadKey("data"))`

```
      request.done (response)=>
        data = @store.normalize 'user', response
        @store.pushPayload 'user', data
```
