### ISSUE TITLE
Unable to send meta data in GET response without including pagination attributes

### ISSUE THREAD

**Issue by indvinoth** [dustinfarris/ember-django-adapter#147]
Currently we are invoking a GET request to Django with some filter parameters applied. The results wont be more than 20 or 30, so we are not using pagination. 

The problem is we are unable to send meta data without the pagination attributes due to the following check in the `normalizeResponse` function

      if (!Ember.isNone(payload) &&
          payload.hasOwnProperty('next') &&
          payload.hasOwnProperty('previous') &&
          payload.hasOwnProperty('results')) {
          ...
      }

So we are sending dummy count, next and previous values and adding our meta data along with the results array. 
Could some one please suggest me a better way of doing this or to stick with the current approach?
Thank you.

**Comment by benkonrath** [comment]
Thanks for letting us know about this issue. I didn't anticipate this use case when I developed the pagination support but I can adjust `normalizeResponse` to handle it.

**Comment by indvinoth** [comment]
@benkonrath  thanks for your quick response. I will stick to current approach (sending dummy pagination attributes) till the `normalizeResponse` is adjusted :smile:

**Comment by dustinfarris** [comment]
@indvinoth would you mind sharing your Django REST Framework view that is adding additional metadata?  I am curious about how this works.

**Comment by indvinoth** [comment]
@dustinfarris  Sure

**Comment by indvinoth** [comment]
Sorry for the delayed response @benkonrath, @dustinfarris. Diwali holidays here in India. 

To make it work we have extended the default pagination class from Django and used it in the viewset. Count, next and prev meta are added as part of pagination and we have set the page size to 30 since the items will not be more than 20.

The following JSON response is received from the Django REST API.

    {
       "next": null,
       "time_left": 1447351200,
       "previous": null,
       "count": 0,
       "results": [...]
     }

**Comment by dustinfarris** [comment]
Thanks @indvinoth.  Can you share the view (in Python) that is generating this response?

**Comment by indvinoth** [comment]
Please find the code for view below which is generating the response.

View:

```
class PostViewSet(viewsets.ModelViewSet):
    """
    List all Posts, or create/ edit/ delete a post.
    """
    queryset = posts_models.Posts.objects.all()
    serializer_class = posts_serializers.PostsSerializer
    parser_classes = (JSONParser, MultiPartParser,)
    authentication_classes = (TokenAuthentication,)
    permission_classes = (posts_permissions.IsAuthenticated, posts_permissions.StaffAccessPermission)
    pagination_class = posts_pagination.CustomPagination

    @posts_decorators.filter_posts  # queryset is tweaked here
    def list(self, request):
        return super(PostViewSet, self).list(request)
```
Pagination:

```
class CustomPagination(pagination.PageNumberPagination):
    page_size = 50
    page_size_query_param = 'page_size'
    max_page_size = 50

    def get_paginated_response(self, data):
        return response.Response({
            'next': self.get_next_link(),
            'previous': self.get_previous_link(),
            'time_left': time_left,
            'current_time': current_unix_time,
            'count': self.page.paginator.count,
            'results': data
        })
```

Actually the backend python code is written by another developer. If possible, I will try to loop him to this discussion.

**Comment by benkonrath** [comment]
@indvinoth Thanks and sorry for the delay in getting back to you on this.

It looks like you'll still need to use the DRF pagination setup with the `CustomPagination` class to set your custom list metadata. This means you'd be using the DRF pagination setup for non-pagination metadata which seems like it's not a commonly agreed upon way to get this list metadata. I'm not saying that your approach is wrong, it just doesn't seem like a standard way to do this. For instance, here is another way to deal with metadata in DRF.

http://www.django-rest-framework.org/api-guide/metadata/

In the end, removing the check for `next` and `previous` effectively makes `results` a reserved field which is not something we want (see #148 for a discussion about this).

If you don't want to include `next` and `previous` in your API, just override `normalizeResponse` to create a custom version for your use case. You can cut and paste the current version and replace this snippet:
```
    if (!Ember.isNone(payload) &&
      payload.hasOwnProperty('next') &&
      payload.hasOwnProperty('previous') &&
      payload.hasOwnProperty('results')) {
```

with this snippet:
```
    if (!Ember.isNone(payload) && payload.hasOwnProperty('results')) {
```
