### ISSUE TITLE
DRF CursorPagination

### ISSUE THREAD

**Issue by erichonkanen** [dustinfarris/ember-django-adapter#150]
Hello,

I am trying to implement pagination using the [CursorPagination](http://www.django-rest-framework.org/api-guide/pagination/#cursorpagination) class from drf, is this possible? I know the PageNumberPagination class works out of the box but I need to use CursorPagination and I am getting an error in the client when I switched to using it.

`message: "Assertion Failed: You must include an 'id' for message in an object passed to 'push'"`

```
  loadPaginatedMessages: (page)->
    ### Loads a paginated set of messages from a group.
    @param {page} The optional page number to be loaded.
    ###
    group = @get 'content.groupId'

    onSuccess = (result)=>
      # Populate the messages array.
      result.forEach (msg, index)=>
        @get('messages').pushObject msg

      # Set the `activeGroup` for use later.
      @set 'activeGroup', group

      # Set isLoading to false since we are loaded now.
      @set 'isLoading', false

      # Set the next paginated page.
      @set 'nextPaginatedPage', result.get 'meta.next'

    onError = (error)=>
      # {error} - an error occurred while loading messages.
      log "error: ", error

    params =
      group: group
    @get('store').query('message', params).then onSuccess, onError
```

```
class MessageResultsPagination(CursorPagination):
    page_size = 15
    ordering = '-created_at'


class MessageViewSet(viewsets.ModelViewSet):
    pagination_class = MessageResultsPagination
    serializer_class = serializers.MessageSerializer
```

ps: do you know if there is a way to reverse the ordering of PageNumberPagination? e.g. load the last page first etc... I didn't think there was a way to do it which is why I need CursorPagination (plus it will be a large dataset)

**Comment by erichonkanen** [comment]
edit: I just noticed this http://dustinfarris.com/ember-django-adapter/pagination/#cursor-pagination

However I updated my `app/serializers/message.coffee` to below and I still get same error (added debugger and it seems like `extractPageNumber` isnt even called?)

```
import DRFSerializer from './drf'

MessageSerializer = DRFSerializer.extend
  attrs:
    user: key: 'user_id'
  extractPageNumber: (url)->
    debugger
    match = /.*?[\?&]cursor=([A-Za-z0-9]+).*?/.exec url
    if match
      return match[1]
    return null

export default MessageSerializer
```

**Comment by dustinfarris** [comment]
@erichonkanen what version of ember-data and ember-django-adapter are you using?

**Comment by erichonkanen** [comment]
@dustinfarris 

    "ember-data": "1.13.9",
    "ember-django-adapter": "1.1.1",

**Comment by benkonrath** [comment]
As far as I know, this addon isn't compatible with ember-cli-coffeescript (see #121). Is it possible for you to try with javascript just to narrow the problem down a bit?

**Comment by erichonkanen** [comment]
@benkonrath @dustinfarris I narrowed it down to a conditional that failed in 1.1.1

https://github.com/dustinfarris/ember-django-adapter/blob/v1.1.1/addon/serializers/drf.js#L96

DRF doesn't return `count` in the payload so it always failed.. looks like that was removed in 1.1.2 though
