### ISSUE TITLE
Question: Remove trailing slash from query?

### ISSUE THREAD

**Issue by ryfo18** [dustinfarris/ember-django-adapter#152]
I'm doing the following in a route:

this.store.query("user", {auth_path: params.auth_path});

This issues a GET request to my API, but the url is formatted as: /api/users/?auth_path=auth_path_example

Is there an easy way to remove the trailing-slash after users in the url?

**Comment by ryfo18** [comment]
It appears this isn't really an issue for me. My apologies. I was able to make DRF work just fine w/ this format.

**Comment by dustinfarris** [comment]
Sorry for not getting to this right away.  For reference we have some documentation on trailing slashes here: http://dustinfarris.com/ember-django-adapter/trailing-slashes/
