### ISSUE TITLE
store.queryRecord empty response throws error

### ISSUE THREAD

**Issue by erichonkanen** [dustinfarris/ember-django-adapter#153]
Hello,

I am making a request to my backend that is returning an empty array (no records) as `[]`, however I'm now getting this `"Assertion Failed: store.queryRecord expected the adapter to return one record but the response from the adapter was empty."`

Is this something I need to change on my backend to use a json-api response where things are stuffed inside [{data: []}] or is this something that this package should handle?

**Comment by benkonrath** [comment]
I think it should work so there might be a problem with the adapter. Which version of Ember, Ember Data and Django REST Framework are you using?

**Comment by erichonkanen** [comment]
ember: 2.4.2, ember-data: 2.4.0, DRF: 3.2.4

**Comment by benkonrath** [comment]
It looks like the tests are failing for Ember / Ember Data >= 2.1. That PR allows the tests to run again. I'll try to get look into this next week but I'm pretty busy at the moment so I can't promise anything. At least you can run the tests and maybe try to figure out what the problem is.

**Comment by pangratz** [comment]
@erichonkanen this is a regression which has been fixed in emberjs/data#4256 and is included in ember-data `v.2.5.0`. Can you try to update ember-data to this version and check if it works again as expected?

**Comment by erichonkanen** [comment]
hey, ok yes let me try

**Comment by dustinfarris** [comment]
@erichonkanen is this still an issue for you after upgrading ember-data?

**Comment by erichonkanen** [comment]
closing for now as I haven't confirmed it but if it pops up again ill return
