### ISSUE TITLE
XMLHttpRequest cannot load....

### ISSUE THREAD

**Issue by tastebud** [dustinfarris/ember-django-adapter#155]
Thanks for your work on this adapter.

I am receiving the following error on a GET request

`XMLHttpRequest cannot load https://api.quarqrace.com/api/v1/races/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access.`

I found your answer to this situation on stackoverflow: http://stackoverflow.com/questions/33587349/not-able-to-make-request-to-backend-server-in-ember-error-no-access-control-a/33613549#33613549

The solution you proposed required modification on the server, is this the only way?  I can access the JSON from my browser at https://api.quarqrace.com/api/v1/races/?format=json

Here is the Response Header:
`HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 2790
Connection: keep-alive
Allow: GET, POST, HEAD, OPTIONS
Cache-Control: max-age=0
Cache-Control: public,max-age=10
Content-Encoding: gzip
Date: Thu, 24 Mar 2016 23:11:16 GMT
Expires: Thu, 24 Mar 2016 23:11:16 GMT
Last-Modified: Thu, 24 Mar 2016 23:11:16 GMT
Server: nginx/1.8.0
Vary: Accept
X-Frame-Options: SAMEORIGIN
X-Cache: Miss from cloudfront
Via: 1.1 1de8c600b9b99e57b61a04b0965781b9.cloudfront.net (CloudFront)
X-Amz-Cf-Id: PAHLLR-PfTw_EuLRYCLU7u0cSAnZ8mpXrjSBdzDLgtMKNq3hhpAR5w==
Request Headers
view source
`

Thanks for your help!

**Comment by tastebud** [comment]
Using curl I was able to get a JSON response using -u and -H flags; without those flags I receive the same response headers.  Is there a way I can add these attributes to the headers to the request generated by ember-django-adapter?

Both curl requests are show below in case that helps.

Thanks again,
Wayne

Without the flags:
~ 🍔  curl -I https://api.quarqrace.com/api/v1/races/
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Allow: GET, POST, HEAD, OPTIONS
Cache-Control: public,max-age=10
Date: Fri, 25 Mar 2016 00:42:46 GMT
Server: nginx/1.8.0
Set-Cookie: csrftoken=ZrjNDFRdEslNAxwwpo3dvbN2PC0rMvzp; expires=Fri, 24-Mar-2017 00:42:46 GMT; Max-Age=31449600; Path=/
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN
X-Cache: Miss from cloudfront
Via: 1.1 1f5200ace72953cff28f9982c5f15365.cloudfront.net (CloudFront)


With the flags:
~ 🍔  curl -u wayne@iofusion.com:passwordEditedOut -H "Accept: application/json" https://api.quarqrace.com/api/v1/races/
[{"id":447,…..}]

**Comment by orf** [comment]
Your requests are going across origins, so they are subject to the cross origin resource sharing standard. There is no way to make your browser connect to 'api.quarqrace.com' without them setting the access-control-allow-origin heading.

One way around this is to make your API act as a proxy to the API in request, i.e "api.yoursite.com/api/v1/races" makes your backend make a request to "api.quarqrace.com".

**Comment by tastebud** [comment]
Thanks for the response.  I was able to get the server team to update CORS headers and now things are running smoothly.
