### ISSUE TITLE
Why does register-version.js still mentions 1.1.1?

### ISSUE THREAD

**Issue by planetexpress69** [dustinfarris/ember-django-adapter#156]
Just a probably stupid question as I a not that into the world of ember modules.

**Comment by benkonrath** [comment]
It was just an oversight with the last release. See the comments on this commit:

https://github.com/dustinfarris/ember-django-adapter/commit/92b466b132df3b56610e5ee21ac1d8f0714402c6

**Comment by planetexpress69** [comment]
Thanks for letting me know!

--
