### ISSUE TITLE
how to handle errors?

### ISSUE THREAD

**Issue by hoIIer** [dustinfarris/ember-django-adapter#159]
Hello,

Does this package support error handling to play nicely w/ember/json-api? I am noticing that my django rest backend is returning errors in 2 formats depending if it's an `ember-data` request or an `ember-ajax` request and I'm having to hack together error objects in the client...

With ember-data I am getting an error response which is an Array of objects that look like (this is what it looks like in chrome inspector):

```
Object {source: Object, detail: "Please enter a url.", title: "Invalid Attribute"}
detail: "Please enter a url."
source: Object
    pointer: "/data/attributes/source_url"
title: "Invalid Attribute"
```

However in this case my only reference to the field is under `pointer` which makes it a hack to grab that for my use case.

The actual network response is showing:

```
{title: ["Please enter a title."], source_url: ["Please enter a url."]}
source_url: ["Please enter a url."]
    0: "Please enter a url."
title: ["Please enter a title."]
    0: "Please enter a title."
```

So in this case how can I improve this? ideally id like to keep ember-specific formatting (e.g. json-api) in the client so my api can remain client-agnostic... how are you guys handling this? how can I improve? thanks!

**Comment by dustinfarris** [comment]
The object your getting in ember-data is JSON API format.  (the adapter does this intentionally)

See [docs for JSON API error objects](http://jsonapi.org/format/#error-objects)

ember-data wants the errors formatted this way.  The errors _should_ propagate to the object's `errors` attribute automatically for you.  e.g.:

```js
newUser.save().then(user => {
  console.log('success!');
}).catch(response => {
  console.log(newUser.get('errors'));
});
```

**Comment by erichonkanen** [comment]
@dustinfarris it does populate the `errors` property but it is in the format as above which makes it hard/ugly to strip out the field name...
```
      onError = (response)=>
        # Delete the record from the client since it failed.
        content.deleteRecord()
        # Cycle through errors and set the property.
        errors = []
        for error in response.errors
          # For now we must strip the field name from the pointer.
          _f = error.source.pointer.split('/')
          field = _f[_f.length - 1]
          # Push the error key and value into the array.
          errors.push key: field, value: error.detail
        @set 'errors', errors
```
ideally I wouldn't need that `_f = ...`

**Comment by dustinfarris** [comment]
@erichonkanen you're reading errors from the response object, which gives you the raw JSON API object.  The idea is that ember-data will interpret that and propagate it to your ember data model that you were trying to save.  See above I am getting `errors` from the model, not the response.  Try that and see if you get a better result.

**Comment by erichonkanen** [comment]
ok let me check..

**Comment by erichonkanen** [comment]
@dustinfarris if I do `content.errors` how do I know which fields have errors?

**Comment by dustinfarris** [comment]
@erichonkanen i'm not sure what the best javascript is to inspect the errors.  i usually just refer to them in the templates, e.g. (excerpt of a signup form—email field):

```hbs
<div class="form-group {{if model.errors.email 'has-error'}}">
  {{#each model.errors.email as |error|}}
    <p class="text-danger">{{error.message}}</p>
  {{/each}}
  {{input id="id_email" value=model.email type="email" class="email form-control" viewName="email"}}
</div>
```

**Comment by erichonkanen** [comment]
@dustinfarris ok closing this for now... for my use case I need to grab the data inside an action so ideally there'd be a cleaner way to get the field name but its not mission critical! thanks

**Comment by erichonkanen** [comment]
hello, I'm back.. so I'm running into this again and trying to wrap my head around error handling. We are running into an issue where we need to also include the http `status_code` and an application-level `code` key in the json-api error. How should we handle this? Do I need to modify django-rest-framework to include that information and if so in what format?
