### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by erichonkanen** [dustinfarris/ember-django-adapter#160]
hello, I just rebuilt my docker images/containers and for some reason I'm suddenly getting a call stack exceeded error that *may* or may not be from this package... any ideas?

http://i.imgur.com/igJ6gtz.png

**Comment by dustinfarris** [comment]
Have not seen this before.  Can you provide more info, perhaps what the payload was?

**Comment by dpatterson-aio** [comment]
i'm seeing this as well, when the server returns a 400. it seems that the DRF adapter expects the server's error message to be in a specific format, and gets into an infinite loop trying to read the message, when it is not in this format.

for example, we have an `asset` model, and running
```javascript
this.get('store').query('asset', {query: "invalid_query"})
  .then(success => console.log('success!'))
  .catch(error => console.log('error!'));
```
doesn't log anything. the console shows that Maximum call stack exceeded error, and a little digging shows that the function `_drfToJsonAPIValidationErrors` gets into an infinite loop.

that function gets called with `payload = {query: "Failed to parse query: invalid_query"}` in this case (as returned by the server) and gets stuck trying to drill down into the error message object.

i.e. `_drfToJsonAPIValidationErrors` gets called with:

1. `{query: "Failed to parse query: invalid_query"}`
2. `"Failed to parse query: invalid_query"`
3. `"F"`
4. `"F"`
5. ...etc

**Comment by dpatterson-aio** [comment]
do you think this is a problem with `ember-django-adapter`, in that it's too sensitive/unable to detect unformatted error messages? or is there an assumption that django apps must always format their 400 messages in this way?

**Comment by dustinfarris** [comment]
@dpatterson-aio yeah it looks like there needs to be a fallback for errors not stemming from DRF serializers.  Guessing this should probably skip trying to parse the errors altogether and just fail with the raw server response.

**Comment by benkonrath** [comment]
@dpatterson-aio Can you see if #165 solves your problem?

**Comment by dpatterson-aio** [comment]
@benkonrath awesome -- looks like it will! i'll let you know

**Comment by dustinfarris** [comment]
@dpatterson-aio as soon as you confirm this is resolved on master we'll get a release out

**Comment by orf** [comment]
Hey, I can't test this as I'm off on my holidays. Sorry!

**Comment by dpatterson-aio** [comment]
@dustinfarris confirmed -- this issue is resolved for me on master. thanks!

**Comment by dustinfarris** [comment]
Great, thanks for confirming!
