### ISSUE TITLE
How to get nested model data

### ISSUE THREAD

**Issue by Zorig** [dustinfarris/ember-django-adapter#162]
Hi, I am using Django(1.9) DRF(3.4)+Ember2.6, ember-django-adapter. I have tried using [stackoverflow in this url](http://stackoverflow.com/q/38840554/2629235) But no answer. I want to get tasks under project id. I have tried embedded records mixin but no luck. Can anyone help me to figure this out?

I got following response on this url `http://localhost:8000/api/projects/4` : 

    {
        "id": 4,
        "title": "test1 project",
        "description": "some project",
        "owner": "test1"
    }

also following response in `http://localhost:8000/api/projects/4/tasks` : 

	{
		"count": 2,
		"next": null,
		"previous": null,
		"results": [
			{
				"id": 5,
				"title": "4th",
				"description": "4tg description"
			},
			{
				"id": 6,
				"title": "",
				"description": ""
			}
		]
	}

and my Ember model is : 

ember app's project model

    export default Model.extend({
      title: attr(),
      description: attr(),
    });

ember app's task model

    export default Model.extend({
      title: attr(),
      description: attr(),
      due_date: attr('date'),
      assign: belongsTo('user'),
      project: belongsTo('project')
    });

On Django side:

django models:
    
    class Project(models.Model):
        """Canara project """
        title = models.CharField(max_length=50, blank=True, default='')
        created = models.DateTimeField(auto_now_add=True)
        description = models.CharField(max_length=255, blank=True)
        active = models.BooleanField(default=True)
        owner = models.ForeignKey(User, related_name='projects', null=True)

        def __unicode__(self):
            return self.title

    class Task(models.Model):
        title = models.CharField(max_length=55, blank=True)
        description = models.CharField(max_length=255, blank=True)
        created = models.DateTimeField(auto_now_add=True)
        due_date = models.DateField(blank=True, null=True)
        assign = models.ForeignKey(User, null=True)
        project = models.ForeignKey(Project, null=True)

serializer:

	class ProjectViewSet(ModelViewSet):
		"""
		API endpoint for project
		"""
		authentication_classes = [TokenAuthentication, SessionAuthentication]
		permission_classes = (IsAuthenticated, IsOwner)
		serializer_class = ProjectSerializer

		def get_queryset(self):
			"""
			Get user's project
			"""
			return Project.objects.filter(members__member=self.request.user)
			
		def perform_create(self, serializer):
			"""
			Set user as an owner when create project
			"""
			serializer.save(owner=self.request.user)

	class TaskViewSet(ModelViewSet):
		"""
		API for task
		"""
		authentication_classes = [TokenAuthentication, SessionAuthentication]
		permission_classes = [IsAuthenticated,]
		serializer_class = TaskSerializer
		queryset = Task.objects.all()

**Comment by dustinfarris** [comment]
Commented on your SO post
