### ISSUE TITLE
Allow addon to be used as a nested addon

### ISSUE THREAD

**Issue by Sinled** [dustinfarris/ember-django-adapter#163]
Currently there is a problem when you try using addon inside other addon,
build will fail because of wrong parameter passed to included function of addon,
see details:
ember-cli/ember-cli#3718

**Comment by dustinfarris** [comment]
What addons are using ember-django-adapter?

**Comment by Sinled** [comment]
In our company we have whole application as ember addon.

**Comment by dustinfarris** [comment]
Closed in #164
