### ISSUE TITLE
Can't install latest 1.1.3 via npm

### ISSUE THREAD

**Issue by erichonkanen** [dustinfarris/ember-django-adapter#166]
![image](https://cloud.githubusercontent.com/assets/230757/18414965/b23ea2d2-7794-11e6-9ca7-77a11da4a490.png)

**Comment by erichonkanen** [comment]
`npm show ember-django-adapter` shows 1.1.2 for me

**Comment by dustinfarris** [comment]
Thanks for reporting—forgot to publish to npm.  You should be able to install it now.
