### ISSUE TITLE
DEPRECATION: The adapter returned an array for the primary data of a `queryRecord` response. This is deprecated as `queryRecord` should return a single record.

### ISSUE THREAD

**Issue by vecdeque** [dustinfarris/ember-django-adapter#168]
First off, thanks for the excellent work on this addon. Ive used it on a number of projects and it has saved me a ton of time.

Ive recently made the jump to the 2.10.x series of ember-data, and began receiving this deprecation warning. 

```DEPRECATION: The adapter returned an array for the primary data of a `queryRecord` response. This is deprecated as `queryRecord` should return a single record. [deprecation id: ds.serializer.rest.queryRecord-array-response]```

I haven't been able to find a issue or pull request that has already been opened to address this.

If my understanding of this is correct, we can detect the version of ember-data running, and return an array for older version of ember-data, or a single record for newer versions.

Im happy to put in the work for this, but as it might be considered a breaking change depending on who you ask I wanted to raise the issue before putting in the work. If the maintainer prefers a different implementation to address the issue I would still be happy to do the work, but I would like consensus before opening a PR.

**Comment by dustinfarris** [comment]
Thanks for reporting!  I've started the process to upgrade the internal ember-cli for this addon (currently 1.13).  There are now 2 LTS versions of ember out and it's time to drop support for <2.0.

Once that's done we can address this deprecation.

**Comment by kolybasov** [comment]
@dustinfarris I am sure #207 resolved this and maybe some another issues.

https://github.com/kolybasov/ember-django-adapter/blob/7d391fd92932ab6bee04706d4caf9216b5e25b32/addon/serializers/drf.js#L123-L128

**Comment by dustinfarris** [comment]
@vecdeque please reopen if you continue noticing this after upgrading.
