### ISSUE TITLE
Adding headers to requests

### ISSUE THREAD

**Issue by bleib1dj** [dustinfarris/ember-django-adapter#169]
We're trying to pass an API key via a header definition to my Django application. We've modified the adapter file (`adapters/application.js`) in the following way:

```
import Ember from 'ember';
import DRFAdapter from './drf';
import ENV from 'cda-fe/config/environment';

export default DRFAdapter.extend({
  headers: {
    "apikey": ENV.apikey
  },
  pathForType: function(type) {
    const underscored = Ember.String.underscore(type);
    return Ember.String.pluralize(underscored);
  }
});
```

We didn't see any documentation outlining how to add headers to the request. So perhaps this is expected behavior rather than an issue. If that's the case I would request the ability to add headers to the adapter.

**Comment by dustinfarris** [comment]
Hey @bleib1dj!  You did it right!  DRFAdapter extends RESTAdapter which provides the [headers hook](http://emberjs.com/api/data/classes/DS.RESTAdapter.html#toc_headers-customization) that you are using.  Is it not working?

**Comment by bleib1dj** [comment]
Hey @dustinfarris thanks for the quick reply! It doesn't appear to be. If I send an equivalent request using postman with the header set the API responds to the request with a 200. I'm working on getting the actual request being generated by the adapter so that I can specifically identify that the header isn't being added.

**Comment by dustinfarris** [comment]
Ok!  Let me know what you find

**Comment by bleib1dj** [comment]
@dustinfarris turned out to just be a slew of CORS issues. The first being not adding the custom header to `CORS_ALLOW_HEADERS` on the Django side and then some CORS configuration issues on our API Gateway. My apologies for wasting your time :/. Thanks for the assistance though! Was good to know that I was at least on the right track on the ember side!
