### ISSUE TITLE
What are the advantages/disadvantages of using this package vs django-rest-framework-json-api?

### ISSUE THREAD

**Issue by erichonkanen** [dustinfarris/ember-django-adapter#170]
I'm just curious if there are any tradeoffs for handling this on the client versus the backend? We've been using this package for awhile but we're debating moving to handling it on the server with https://github.com/django-json-api/django-rest-framework-json-api to take advantage of json-api spec exception handling and to trim the client down... Curious if anyone has input on this?

**Comment by dustinfarris** [comment]
both are great approaches.  choosing one likely depends on your API needs.  if JSON API clients (Ember) are your _only_ clients, then modifying DRF directly could make sense.  if you have other clients already depending on the existing DRF format, and want to add Ember into the mix, then Ember Data adapter is the right tool for you.

**Comment by erichonkanen** [comment]
@dustinfarris do you have any input on adding custom app-level error codes when using this?
