### ISSUE TITLE
Acceptance test fails because CRUD operation didn't finish up before app shutdown

### ISSUE THREAD

**Issue by OleRoel** [dustinfarris/ember-django-adapter#212]
The pull request https://github.com/dustinfarris/ember-django-adapter/pull/211 got rejected by acceptance test. The reason is that the test app shuts down before the save operation has finished his task. The fix for unit tests is described here:

https://github.com/danielspaniel/ember-data-factory-guy/issues/104

and here:

https://github.com/emberjs/guides/issues/909

**Comment by dustinfarris** [comment]
Hi @OleRoel, thanks for digging into this.  Any chance you can send in a fix?

**Comment by OleRoel** [comment]
@dustinfarris yes, I will try to to fix the unit test tomorrow and send you a pull request. It only depends on my workload.

**Comment by benmurden** [comment]
@dustinfarris @OleRoel I'm working on this now and will hopefully have something for you soon.

**Comment by OleRoel** [comment]
@benmurden Thanks a lot! I had a lot of other things to handle in the last months and appreciate that someone else picks up  the task.
