### ISSUE TITLE
Easy to get multiple versions of ember-data

### ISSUE THREAD

**Issue by ef4** [dustinfarris/ember-django-adapter#219]
This addon has a direct dependency on ember-data. That's a problem because it means it's likely to bring its own version that is different from what the app is using. This causes ember-cli to smash together both versions and include all the resulting files in your app, which is... not great.

This addon should probably move ember-data to `peerDependencies` so that it's guaranteed to share the same copy as the app.

**Comment by dustinfarris** [comment]
Fixed in #220
