### ISSUE TITLE
Website/Documentation 404

### ISSUE THREAD

**Issue by benmurden** [dustinfarris/ember-django-adapter#221]
Readme currently shows "Website" as http://dustinfarris.com/ember-django-adapter/, which returns a 404. As far as I know, the documentation is not hosted anywhere else.

**Comment by dustinfarris** [comment]
Thanks, I'll work on getting this back up

**Comment by Subaku** [comment]
Wanted to give this a bump. In need of this addon but can't get to the documentation.

**Comment by creyD** [comment]
That must have been a huge outage... @dustinfarris

**Comment by Parrryy** [comment]
Yeah still down, do you need help at all?

**Comment by gojefferson** [comment]
Hi @Parrryy, maybe the documentation could be re-posted as a wiki on GitHub. Do you have any experience setting them up?

**Comment by dustinfarris** [comment]
Sorry for the radio silence.  Yes I need help with this.  Open to ideas and happy to do whatever needed administratively.  I will open a general request for maintainers in a separate issue.

Dustin

**Comment by Parrryy** [comment]
@dustinfarris Happy to help where I can. @gojefferson Not particularly but happy to look into and help out.

**Comment by dustinfarris** [comment]
I've updated the domain/url to dustinfarris.github.io/ember-django-adapter which should solve the http error issues.  The formatting and content of the docs could use some love if anyone cares to contribute.
