### ISSUE TITLE
Import AdapterError and InvalidError from "DS" object

### ISSUE THREAD

**Issue by gojefferson** [dustinfarris/ember-django-adapter#226]
See: https://github.com/dustinfarris/ember-django-adapter/pull/225

This is the easiest way to ensure compatibility from 2.16 to the latest of Ember Data. This PR should pass CI, and it will enable user's of ember-django-adapter to upgrade to the latest version of Ember Data (currently they cannot).

**Comment by dustinfarris** [comment]
Fixed in #225
