### ISSUE TITLE
No release with latest commits

### ISSUE THREAD

**Issue by gojefferson** [dustinfarris/ember-django-adapter#228]
Hey @dustinfarris could you please create a new release? The current release doesn't include some of the recent bugfixes, and it's not compatible with the current version of ember data.

BTW, if you'd like to add me as a maintainer of this repo, I would be happy to create the release.

**Comment by dustinfarris** [comment]
Thanks for volunteering.  Yes, I could use help maintaining this.  You've been invited to be a collaborator here—would you mind taking care of the version bump as well?

Please see https://github.com/dustinfarris/ember-django-adapter/commit/489d0113eedc8b5efee0604a12f5af6df094a911 for version bump example.  (note the two places that the version number needs to be updated)

I also typically copy+paste the changelog over to the GitHub release notes for the tag:

e.g. https://github.com/dustinfarris/ember-django-adapter/releases/tag/v2.1.0

What is your npm username?  Guessing gojefferson but don't want to assume.

**Comment by gojefferson** [comment]
Yep, I'll handle the version bump. My npm account is casefleet: https://www.npmjs.com/~casefleet

**Comment by dustinfarris** [comment]
Great!  Invitation sent.  Thanks for doing this.

**Comment by gojefferson** [comment]
Done. Let me know if I missed anything or did anything incorrectly @dustinfarris

**Comment by dustinfarris** [comment]
Looks great.  I did add my opinion to your PR, but I don't think it's worth reverting anything.  Thanks again.
