### ISSUE TITLE
Investigate why it's not possible to set an empty host for the integration tests

### ISSUE THREAD

**Issue by benkonrath** [dustinfarris/ember-django-adapter#33]
A cut & paste from a comment in PR #18:

> It turns out that Pretender doesn't work when the host is set. I ended up setting API_HOST to an   empty string and overriding the default adapter creation to set 'test-host' in the unit tests.

> I tried to override the host setting in the integration tests instead, but nothing I tried worked. There are some facilities for this - like overriding delegate when using moduleFor() - but it didn't work. I also tried writing my own module wrapper like moduleFor() that also didn't work. I'll post a question on the ember-discussion board to see how the host can be overridden to blank for Pretender but it would be great to get this merged as is so I can continue with the integration tests for CRUD failure.

**Comment by gone** [comment]
I'm hitting this issue using ember-mirage and the DRF adapter. Ember tries to use a full url including http during tests, which pretender refuses to honor with the error 
`Error: Pretender will not respond to requests for URLs. It is not possible to accurately simluate the browser's CSP. Remove the http:// from <url>`

Setting the api host to empty to try and use pretender causes tests to halt.

**Comment by dustinfarris** [comment]
Closing for now as this doesn't appear to be blocking anything.
