### ISSUE TITLE
namespace not being set

### ISSUE THREAD

**Issue by dbinetti** [dustinfarris/ember-django-adapter#4]
PREFACE: I am a complete and total noob, so forgive me if I'm missing something, but the namespace parameter does not seem to be honored when making requests of the API.  

My config:
```  
if (environment === 'development') {
    ENV.APP.API_HOST = 'http://localhost:8000';
    ENV.APP.API_NAMESPACE = 'api';
  }
```

In console:
```
Ember Debugger Active VM2701:161
GET http://localhost:8000/photos/?_=1406356846939 404 (NOT FOUND) vendor.js:9726
Error while processing route: photos vendor.js:17062
```

Notice that it is hitting the root url.  Also, if I change my API itself to serve at the root, all is well.

**Comment by jsalva** [comment]
I'm having the same issue using 0.5.1 from ember-cli; I noticed the docs example uses NAMESPACE rather than API_NAMESPACE. However, neither of these are changing adapter urls from root.

**Comment by dustinfarris** [comment]
@jsalva I've been having a lot of issues with ember-cli 0.1.7.  I actually downgraded to 0.1.5.

It looks like 0.1.8 and 0.1.9 were [released today](https://github.com/ember-cli/ember-cli/releases).  Let's try that out and see if it resolves anything.

**Comment by jsalva** [comment]
sadly, upgrading to 0.1.9 didn't help.
It's not terribly difficult for me to set that stuff in an application adapter, but it'd be nice to be able to configure that in the `environment.js` too since it's what the docs recommend

**Comment by dustinfarris** [comment]
@jsalva it should work in the config definitely.  It has been working for me, but something must have changed in ember-cli after 0.1.5.  Something is wrong—thanks for bringing it up.  I will open a new issue to fix this.

**Comment by dustinfarris** [comment]
@jsalva I cannot reproduce this.  I just upgraded to 0.1.9 and everything is working.

Are you configuring the adapter in environment.js like this:

```js
module.exports = function(environment) {
  var ENV = {
    APP: {
      API_NAMESPACE: 'my-api'
    }
  };
  
  ...

  return ENV;
};
```

**Comment by jsalva** [comment]
Yep here it is:

```javascript
//config/environment.js
module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'myapp',
    environment: environment,
    baseURL: '/',
    locationType: 'auto',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
      API_NAMESPACE: 'myapp/api1'
    },


  };
  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    // ENV.APP.LOG_ACTIVE_GENERATION = true;
    ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    // ENV.APP.LOG_VIEW_LOOKUPS = true;

  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.baseURL = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';

  }

  if (environment === 'production') {
    // set this to your production API
  }

  return ENV;
};
```

**Comment by dustinfarris** [comment]
@jsalva Do you have anything in `app/adapters/`?

**Comment by jsalva** [comment]
at first, no (assumed the setting would configure an application adapter w/ my API_NAMESPACE for me. Eventually I just used ember cli to generate `app/adapters/application.js` and put the desired namespace explicitly in there.

**Comment by dustinfarris** [comment]
I really am having trouble reproducing.  Have started a brand new project with `ember new` and the fiddled with the `API_NAMESPACE` setting and everything works as expected.  Can you throw up a quick sample project on GitHub to demonstrate that I can clone and try?

**Comment by dustinfarris** [comment]
@jsalva nevermind.  I have been able to confirm this.  Working on a fix.

**Comment by dustinfarris** [comment]
@jsalva we aren't setting a default `API_HOST` which I believe is the main issue here.  Your namespace is indeed being respected, but it doesn't matter because it was pointed at the ember server.
