### ISSUE TITLE
I don't understand these unmet dependencies

### ISSUE THREAD

**Issue by ewilson** [dustinfarris/ember-django-adapter#44]
Trying to install the adapter, and get all of these. Don't know that it causes a problem, but don't understand how to eliminate them.

    wilsone123 [20:28:34] $ npm i --save-dev ember-django-adapter
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/tiny-lr/node_modules/body-parser requires qs@'2.2.4' but will load
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/tiny-lr/node_modules/qs,
      npm WARN unmet dependency which is version 2.2.5
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream requires readable-stream@'~1.1.9' but will load
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/npm/node_modules/readable-stream,
      npm WARN unmet dependency which is version 1.0.32
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/testem/node_modules/express requires commander@'0.6.1' but will load
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/testem/node_modules/commander,
      npm WARN unmet dependency which is version 2.5.1
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/testem/node_modules/express requires mkdirp@'0.3.3' but will load
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/mkdirp,
      npm WARN unmet dependency which is version 0.5.0
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/testem/node_modules/tap requires glob@'~3.2.1' but will load
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/testem/node_modules/glob,
      npm WARN unmet dependency which is version 3.1.21
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/testem/node_modules/tap requires nopt@'~2' but will load
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/nopt,
      npm WARN unmet dependency which is version 3.0.1
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/testem/node_modules/glob requires minimatch@'~0.2.11' but will load
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/minimatch,
      npm WARN unmet dependency which is version 1.0.0
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/testem/node_modules/fileset requires minimatch@'0.x' but will load
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/minimatch,
      npm WARN unmet dependency which is version 1.0.0
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/testem/node_modules/fireworm requires minimatch@'~0.2.9' but will load
    npm WARN unmet dependency /Users/wilsone123/code/titlematch_web/node_modules/ember-cli/node_modules/minimatch,
      npm WARN unmet dependency which is version 1.0.0
    ember-django-adapter@0.5.0 node_modules/ember-django-adapter
    ~/code/titlematch_web

**Comment by benkonrath** [comment]
Which version of ember-cli are you using?

**Comment by ewilson** [comment]
@benkonrath I'm using 0.1.6 now. I think that I was using 0.1.5 at the time that I posted this. I still see it, in any case.

**Comment by dustinfarris** [comment]
I am not getting this at all.  @ewilson, how are you installing the adapter?

**Comment by ewilson** [comment]
I've included the command in the original post:

    wilsone123 [20:28:34] $ npm i --save-dev ember-django-adapter

I think that I installed node/npm with brew, if that matters ...

**Comment by dustinfarris** [comment]
Can you try doing a clean reinstall of all dependencies?

```
rm -rf node_modules bower_components dist tmp
npm install
bower install
```

Since the `--save-dev` flag should have added ember-django-adapter to your package.json, it should be installed along with everything else now.  Try this and see if you still get those errors.

**Comment by ewilson** [comment]
Executed those commands, they work without error or warning.

If I try again:

    npm i --save-dev ember-django-adapter

I get the same warnings again. (Feel free to close is this doesn't seem important, nothing is actually broken as far as I can tell.)

**Comment by dustinfarris** [comment]
ok, i still can't reproduce.  please feel free to open a new issue if this becomes problematic in the future.
