### ISSUE TITLE
gh-pages still trying to run tests

### ISSUE THREAD

**Issue by dustinfarris** [dustinfarris/ember-django-adapter#55]
I [moved the circle config](https://github.com/dustinfarris/ember-django-adapter/commit/351e78684cda23418fb47d8c22aaf3598cbfdda1) from @benkonrath [over to the gh-pages branch](https://github.com/dustinfarris/ember-django-adapter/commit/c666d777e9d310d8ce7b8e422090832116bee697) so that it would get picked up by CircleCI at the right time only to discover that the entire branch gets overwritten every time the docs are generated.

This needs to be added as an artifact to mkdocs I think, just not sure yet how to do it.

**Comment by benkonrath** [comment]
I'm not getting the emails anymore. Maybe you were getting them because the embedded branch didn't yet have the update circle ci conf?

**Comment by benkonrath** [comment]
I see this problem now as well.
