### ISSUE TITLE
HyperLinkedRelatedField support?

### ISSUE THREAD

**Issue by dustinfarris** [dustinfarris/ember-django-adapter#57]
Interesting question/answer: http://discuss.emberjs.com/t/coalescing-find-requests/7076

I didn't know you could supply links to resources with Ember.

So we could, in theory, support the [HyperLinkedRelatedField](http://www.django-rest-framework.org/api-guide/relations/#hyperlinkedrelatedfield) and possibly the [HyperLinkedIdentityField](http://www.django-rest-framework.org/api-guide/relations/#hyperlinkedidentityfield).

This may "just work".  I would like to add documentation if it does.  I will investigate this further.

Relates to #32.

**Comment by benkonrath** [comment]
I'm already using this in my django-filter based solution for async relationships. I can send a PR if you want to check it out but it not done. I've hard coded some stuff so it's not generalized yet.

**Comment by benkonrath** [comment]
I think the code I have already supports the hyperlinked fields. I sort of dropped the ball on this one. I should have had a PR for this already. Sorry about that.

**Comment by benkonrath** [comment]
See PR #58 for more discussion.

**Comment by benkonrath** [comment]
See PR #95 for an implementation of this.

**Comment by dustinfarris** [comment]
Closing in favor of #95
