### ISSUE TITLE
mischaracterizes resources where the name is a singular ending in 's'

### ISSUE THREAD

**Issue by dbinetti** [dustinfarris/ember-django-adapter#60]
I'm not sure if this is a bug or design decision, but I am unable to resolve a specific issues regarding a resource where the singular version of the name ends in 's': specifically, i'm trying to map the resource 'chorus', which creates all sort of issues:  EDA seems to look for the singular version of the endpoint, but the controller then thinks it's an object and not an array, something else starts looking for 'choru' (dropped s) and all sorts of other unpleasantries.

Obviously I can change my endpoint name to whatever on the DRF side, but presumably the point of this adapter is to serve as the gateway without having to touch DRF.  Anyway, would appreciate some guidance or simply a 'yep, that's the design'.  

FWIW, I come down on the 'name all collections singular' side of that particular religious war, but am not so zealous as to do what I have to do to make things work...  :-)

**Comment by benkonrath** [comment]
EDA uses this function to create the paths (endpoints): 

```js
pathForType: function(type) {
  var dasherized = Ember.String.dasherize(type);
  return Ember.String.pluralize(dasherized);
},
```
You can override this in your own app if you don't like this default and make everything singular. Here's a link that should help:

http://emberjs.com/guides/models/customizing-adapters/#toc_path-customization

In your case, you might have to also tell the inflector about how to deal with the word 'chorus' for singular / pluralization. Here's the a link to the docs that should help with this one:

http://emberjs.com/guides/models/the-rest-adapter/#toc_pluralization-customization

Do these suggestions / pointers solve your problem?

**Comment by dbinetti** [comment]
Thank you!  I'll need to better understand how to override using the custom adapters, but that isn't a bug...

**Comment by benkonrath** [comment]
You can run this ember-cli command to generate an adapter that you can override:

```bash
ember generate drf-adapter application
```

This is documented here:

http://dustinfarris.com/ember-django-adapter/extending/

I'm glad I could help you out on this one.
