### ISSUE TITLE
Example project?

### ISSUE THREAD

**Issue by typeshige** [dustinfarris/ember-django-adapter#66]
Could you create an example Django + Ember CLI project that works out of the box?  Thanks!

**Comment by dustinfarris** [comment]
I usually (and recommend) keeping Django and Ember in separate repos.

Example Django: https://github.com/dustinfarris/edatest
Example Ember: https://github.com/dustinfarris/edatest-web

I actually created these to report a (fixed) bug, but they can serve as the most basic possible example.

We intend to create more comprehensive example projects in the future.

**Comment by typeshige** [comment]
Thank you.  I'm going to look at these now.  Perhaps, making it more clear in the docs that these repos exist could help!

**Comment by dustinfarris** [comment]
@typeshige you may be interested in this commit.  https://github.com/dustinfarris/edatest/commit/a4c1f54a4cde15d6d5c636cd4d87fa4935c3c4ff
