### ISSUE TITLE
Download builds without ember-cli?

### ISSUE THREAD

**Issue by riklaunim** [dustinfarris/ember-django-adapter#72]
Is there a build of this adapter that can be downloaded (without the need of using ember-cli)?

**Comment by dustinfarris** [comment]
No.  ember-cli is [slated to become an integral part of Ember](https://github.com/emberjs/rfcs/pull/15) and we are onboard with that vision.

You can reference the [original adapter](https://github.com/toranb/ember-data-django-rest-adapter) which was a standalone build, but it has been deprecated and may not work with recent versions of Ember Data and DRF.
