### ISSUE TITLE
Docs for extending serializer/adapter are wrong?

### ISSUE THREAD

**Issue by jschneier** [dustinfarris/ember-django-adapter#73]
Hi and sorry in advance if I am doing something wrong. I am using the latest version of everything I think and need to extend the adapter. My application is working fine using the default ember data RESTAdapter. I now need to add in drf support and do the following in accordance with the docs:

``ember g drf-adapter application``

My application now immediately errors out in the console with a message of

``Error while processing route: home Could not find module my-sample-app/adapters/drf Error: Could not find module my-sample-app/adapters/drf``

A similar issue happens when I attempt to make a customer serializer, any help would be greatly appreciated. That's a bit of a snipped traceback but it seems pretty obvious what the issue is. I'm not familiar enough with all this to debug it myself, sorry.

**Comment by dustinfarris** [comment]
Hmm, possibly a bug.  What version of ember-cli are you using?

**Comment by dustinfarris** [comment]
It looks like ember-cli 0.2.0-beta has introduced some breaking changes for addons—which we will need to address.  Assuming that's what you are using, you may want to use the latest stable version of ember-cli for now (0.1.15) while we work on support for 0.2.0.

**Comment by jschneier** [comment]
I'm actually on 0.1.11

**Comment by dustinfarris** [comment]
I actually had issues with 0.1.11 myself.  Can you try upgrading to 0.1.15 and see if the problem persists?

**Comment by dustinfarris** [comment]
@jschneier are you still seeing this in recent versions of ember-cli?

**Comment by jschneier** [comment]
Nope, working now. Thanks for your help!

**Comment by progresivjose** [comment]
i have the same problem with ember-cli 0.2.3....

**Comment by dustinfarris** [comment]
Thanks for reporting.  Any way you can see if #81 helps?

**Comment by dustinfarris** [comment]
Please reopen if this issue persists.
