### ISSUE TITLE
cli v0.2.3: default adapter can't import './drf'

### ISSUE THREAD

**Issue by devinrhode2** [dustinfarris/ember-django-adapter#80]
Full error:
```
[Error] Error: Could not find module `wibi/application/drf` imported from `wibi/application/adapter`
	end (vendor.js, line 10728)
	run (vendor.js, line 10770)
	join (vendor.js, line 10789)
	join (vendor.js, line 26509)
	(anonymous function) (vendor.js, line 26564)
	fire (vendor.js, line 3345)
	fireWith (vendor.js, line 3457)
	ready (vendor.js, line 3669)
	completed (vendor.js, line 3700)
```
I'm guessing this is an error with ember-cli `0.2.3`? Should [ember-django-adapter/addon/adapters/drf.js](https://github.com/dustinfarris/ember-django-adapter/blob/master/addon/adapters/drf.js) have been put into the adapters folder?

**Comment by dustinfarris** [comment]
I am working to bring the adapter up to speed with the 0.2.x series which has been a lot of work (mainly for the tests), but I have not run into this specific error—I am using the adapter on a project with ember-cli 0.2.3.  What is your usage like?

**Comment by devinrhode2** [comment]
well I just removed the adapter because it was empty/not doing anything but
causing this error:
https://github.com/devinrhode2/wibi/commit/b9e129f16982ec273741f010f39f0f561c188b66


-Devin <http://zerply.com/DevinRhode2>
<http://zerply.com/devinrhode2>

**Comment by dustinfarris** [comment]
Ah, I see.  Interesting approach at combining your Ember and Django project into one directory using staticdirs.  Most people keep them separate—personally, I keep them in two different repositories altogether.  I'm guessing that your approach is having some side effect on node's ability to traverse dependencies, which would explain the error.  Or perhaps it's something else.

**Comment by dustinfarris** [comment]
@devinrhode2 do you still see this with the latest version of ember-django-adapter?

**Comment by dustinfarris** [comment]
Closing due to no response.  Please feel free to reopen if this issue persists.
