### ISSUE TITLE
Modify signature of adapter methods to match ember-data 1.0.0-beta.16

### ISSUE THREAD

**Issue by holandes22** [dustinfarris/ember-django-adapter#83]
Easy fix as it is only syntactic. Relevant methods are:

- buildURL
- findMany 

I'll take care of this PR, but @dustinfarris I want to hold on until you merge the ember-cli update to 0.2.3, sounds good?

**Comment by dustinfarris** [comment]
Sounds good to me.

**Comment by holandes22** [comment]
Great, can you please label it enhancement and assign it to me?

**Comment by benkonrath** [comment]
Support for ember-cli 0.2.3 has just been merged.

**Comment by holandes22** [comment]
Awesome, I'll get to it tonight

**Comment by benkonrath** [comment]
Fixed via b15bdc1.
