### ISSUE TITLE
ember-data beta.18 doesn't work with v0.5.5 on IE8

### ISSUE THREAD

**Issue by benkonrath** [dustinfarris/ember-django-adapter#98]
I guess something with the deprecation warnings from ember-data beta.18 cause ember-data to fail on IE8. @dustinfarris Any chance you can make a new release soon?

**Comment by dustinfarris** [comment]
Yes, but want to update for [ember-cli 0.2.7](https://github.com/ember-cli/ember-cli/releases/tag/v0.2.7) first.

**Comment by benkonrath** [comment]
Ok, PR coming.

**Comment by dustinfarris** [comment]
You rock!  Merged #99 and [v0.5.6 has been released](https://github.com/dustinfarris/ember-django-adapter/releases/tag/v0.5.6).
